local AnchorText = dofile("koreader-plugin/bookorbit.koplugin/bookorbit_anchor_text.lua")
local value = assert(AnchorText.normalize(" \tA😀\194\160  é\n"))
assert(value.text == "A😀 é")
assert(table.concat(value.nativeOffsets, ",") == "2,3,7,11,12,14")
assert(not value.truncated)
assert(AnchorText.bound("😀é", 2) == "😀e")
assert(AnchorText.normalize("\192\128") == nil)
assert(AnchorText.normalize("\237\160\128") == nil)
assert(AnchorText.normalize("😀", 3).truncated)
assert(AnchorText.normalize("😀", 3).text == "")
assert(AnchorText.normalize("\239\187\191").text == "\239\187\191")
assert(AnchorText.normalize("\t \n").text == "")
print("bookorbit_anchor_text_test.lua: ok")
